services:
  web:
    build: .
    volumes:
      - ./project:/project
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    command: >
      uvicorn project.asgi:application
      --host 0.0.0.0
      --port 8000
      --reload
