# Generated by Django 5.2.7 on 2025-11-01 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('student', '生徒'), ('teacher', '教師'), ('staff', 'スタッフ')], default='student', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
    ]
